(function(factory) {
  var api = factory();
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  if (typeof window !== 'undefined') {
    window.app = window.app || {};
    window.app.caseLibrary = window.app.caseLibrary || {};
    window.app.caseLibrary.runtimeContext = api;
  }
})(function() {
  var DOM_IDS = {
    root: 'caseLibrary',
    status: 'caseLibraryStatus',
    jumpToExecBtn: 'caseLibraryJumpExecBtn',
    autoCaseLibrarySelectBtn: 'autoCaseLibrarySelectBtn',
    caseLibraryImportSelectBtn: 'caseLibraryImportSelectBtn',
    writerDrawerOpenBtn: 'openCaseLibraryWriterDrawerBtn',
    editDrawerOpenBtn: 'openCaseLibraryEditDrawerBtn',
    editCard: 'caseLibraryEditCard',
    editCardTitle: 'caseLibraryEditCardTitle',
    editProject: 'caseLibraryEditProject',
    editVersion: 'caseLibraryEditVersion',
    editFileName: 'caseLibraryEditFileName',
    editSearchInput: 'caseLibraryEditSearchInput',
    editClearSearchBtn: 'caseLibraryEditClearSearchBtn',
    editBatchDeleteBtn: 'caseLibraryEditBatchDeleteBtn',
    editBatchAddCountInput: 'caseLibraryEditBatchAddCountInput',
    editBatchAddBtn: 'caseLibraryEditBatchAddBtn',
    editToExecBtn: 'caseLibraryEditToExecBtn',
    editStatus: 'caseLibraryEditStatus',
    editView: 'caseLibraryEditView',
    editorPaginationTop: 'caseLibraryEditorPaginationTop',
    editorPaginationBottom: 'caseLibraryEditorPaginationBottom',
    editorSelectAll: 'caseLibraryEditorSelectAll',
    editorTableHost: 'caseLibraryEditorTableHost',
    aiGenBtn: 'caseLibraryAiGenBtn',
    xmindViewBtn: 'caseLibraryXmindViewBtn',
    aiGenDrawer: 'caseLibraryAiGenDrawer',
    aiGenDropZone: 'caseLibraryAiGenDropZone',
    aiGenFileInput: 'caseLibraryAiGenFileInput',
    aiGenFileName: 'caseLibraryAiGenFileName',
    aiGenImportStatus: 'caseLibraryAiGenImportStatus',
    aiGenRequirementInput: 'caseLibraryAiGenRequirementInput',
    aiGenClearRequirementBtn: 'caseLibraryAiGenClearRequirement',
    aiGenRunBtn: 'caseLibraryAiGenRunBtn',
    aiGenStatus: 'caseLibraryAiGenStatus',
    aiGenResult: 'caseLibraryAiGenResult',
    aiGenResultBody: 'caseLibraryAiGenResultBody',
    aiGenSelectAllBtn: 'caseLibraryAiGenSelectAllBtn',
    aiGenSelectNoneBtn: 'caseLibraryAiGenSelectNoneBtn',
    aiGenDiscardBtn: 'caseLibraryAiGenDiscardBtn',
    aiGenRegenerateBtn: 'caseLibraryAiGenRegenerateBtn',
    aiGenSelectAllToggle: 'caseLibraryAiGenSelectAllToggle',
    aiGenResultSummary: 'caseLibraryAiGenResultSummary',
    aiGenSelectionHint: 'caseLibraryAiGenSelectionHint',
    aiGenAppendBtn: 'caseLibraryAiGenAppendBtn',
    missingReminderTop: 'caseLibraryMissingReminderTop',
    missingReminderBottom: 'caseLibraryMissingReminderBottom',
    missingCard: 'caseLibraryMissingCard',
    missingCardTitle: 'caseLibraryMissingCardTitle',
    missingProject: 'caseLibraryMissingProject',
    missingModules: 'caseLibraryMissingModules',
    missingBatchDeleteBtn: 'caseLibraryMissingBatchDeleteBtn',
    missingStatus: 'caseLibraryMissingStatus',
    missingView: 'caseLibraryMissingView',
    missingTypePills: 'caseLibraryMissingTypePills',
    missingImportDropZone: 'caseLibraryMissingImportDropZone',
    missingImportInput: 'caseLibraryMissingImportInput',
    missingImportFileHint: 'caseLibraryMissingImportFileHint',
    missingImportProjectSelect: 'caseLibraryMissingImportProjectSelect',
    missingImportConfirmBtn: 'caseLibraryMissingImportConfirmBtn',
    missingImportStatus: 'caseLibraryMissingImportStatus',
    missingImportDiffTitle: 'caseLibraryMissingImportDiffTitle',
    missingImportDiffStatus: 'caseLibraryMissingImportDiffStatus',
    missingImportDiffMeta: 'caseLibraryMissingImportDiffMeta',
    missingImportStructureWrap: 'caseLibraryMissingImportStructureWrap',
    missingImportStructureBody: 'caseLibraryMissingImportStructureBody',
    missingImportDiffBody: 'caseLibraryMissingImportDiffBody',
    missingImportDiffConfirmBtn: 'caseLibraryMissingImportDiffConfirmBtn',
    importDropZone: 'caseLibraryImportDropZone',
    importInput: 'caseLibraryImportInput',
    importFileHint: 'caseLibraryImportFileHint',
    importProjectSelect: 'caseLibraryImportProjectSelect',
    importVersionSelect: 'caseLibraryImportVersionSelect',
    importExcelTemplateTypeSelect: 'caseLibraryImportExcelTemplateType',
    importExcelTemplateBtn: 'caseLibraryImportExcelTemplateBtn',
    importXmindTemplateBtn: 'caseLibraryImportXmindTemplateBtn',
    importConfirmBtn: 'caseLibraryImportConfirmBtn',
    importStatus: 'caseLibraryImportStatus',
    writerPublishDrawer: 'caseLibraryWriterPublishDrawer',
    writerPublishHint: 'caseLibraryWriterPublishHint',
    writerPublishFileNameInput: 'caseLibraryWriterPublishFileNameInput',
    writerPublishFileNameStatus: 'caseLibraryWriterPublishFileNameStatus',
    writerPublishProjectSelect: 'caseLibraryWriterPublishProjectSelect',
    writerPublishVersionSelect: 'caseLibraryWriterPublishVersionSelect',
    writerPublishConfirmBtn: 'caseLibraryWriterPublishConfirmBtn',
    writerPublishStatus: 'caseLibraryWriterPublishStatus',
    importDiffTitle: 'caseLibraryImportDiffTitle',
    importDiffStatus: 'caseLibraryImportDiffStatus',
    importDiffMeta: 'caseLibraryImportDiffMeta',
    importDiffLocateBar: 'caseLibraryImportDiffLocateBar',
    importDiffTableHost: 'caseLibraryImportDiffTableHost',
    importDiffOverwriteBtn: 'caseLibraryImportDiffOverwriteBtn',
    importInvalidTitle: 'caseLibraryImportInvalidTitle',
    importInvalidStatus: 'caseLibraryImportInvalidStatus',
    importInvalidLocateBar: 'caseLibraryImportInvalidLocateBar',
    importInvalidBody: 'caseLibraryImportInvalidBody',
    importInvalidConfirmBtn: 'caseLibraryImportInvalidConfirmBtn',
    importDuplicateTitle: 'caseLibraryImportDuplicateTitle',
    importDuplicateStatus: 'caseLibraryImportDuplicateStatus',
    importDuplicateBody: 'caseLibraryImportDuplicateBody',
    importDuplicateConfirmBtn: 'caseLibraryImportDuplicateConfirmBtn',
    editDrawerProjectSelect: 'caseLibraryEditProjectSelect',
    editDrawerVersionSelect: 'caseLibraryEditVersionSelect',
    editDrawerOwnerFilterSelect: 'caseLibraryEditOwnerFilterSelect',
    editDrawerFileSearchInput: 'caseLibraryEditFileSearchInput',
    editDrawerChangeVersionSelect: 'caseLibraryEditChangeVersionSelect',
    editDrawerChangeVersionBtn: 'caseLibraryEditChangeVersionBtn',
    editDrawerConfirmBtn: 'caseLibraryEditConfirmBtn',
    editDrawerShareBtn: 'caseLibraryEditShareBtn',
    editDrawerExportXmindBtn: 'caseLibraryEditExportXmindBtn',
    editDrawerExportExcelBtn: 'caseLibraryEditExportExcelBtn',
    editDrawerDeleteBtn: 'caseLibraryEditDeleteBtn',
    editDrawerSelectAll: 'caseLibraryEditSelectAll',
    editDrawerStatus: 'caseLibraryEditDrawerStatus',
    editDrawerListBody: 'caseLibraryEditListBody',
    editDrawerPaginationTop: 'caseLibraryEditDrawerPaginationTop',
    editDrawerPaginationBottom: 'caseLibraryEditDrawerPaginationBottom',
    missingDrawerProjectSelect: 'caseLibraryMissingProjectSelect',
    missingDrawerModuleSelect: 'caseLibraryMissingModuleSelect',
    missingDrawerTypeSelect: 'caseLibraryMissingTypeSelect',
    missingDrawerTypeAddBtn: 'caseLibraryMissingTypeAddBtn',
    missingDrawerTypeManageBtn: 'caseLibraryMissingTypeManageBtn',
    missingDrawerTypeGrid: 'caseLibraryMissingTypeGrid',
    missingDrawerQueryBtn: 'caseLibraryMissingQueryBtn',
    missingDrawerAddModuleBtn: 'caseLibraryMissingAddModuleBtn',
    missingDrawerBatchViewBtn: 'caseLibraryMissingBatchViewBtn',
    missingDrawerDeleteBtn: 'caseLibraryMissingDeleteBtn',
    missingDrawerExportXmindBtn: 'caseLibraryMissingExportXmindBtn',
    missingDrawerExportExcelBtn: 'caseLibraryMissingExportExcelBtn',
    missingDrawerSelectAll: 'caseLibraryMissingSelectAll',
    missingDrawerStatus: 'caseLibraryMissingDrawerStatus',
    missingDrawerListBody: 'caseLibraryMissingListBody',
    missingDrawerPaginationTop: 'caseLibraryMissingDrawerPaginationTop',
    missingDrawerPaginationBottom: 'caseLibraryMissingDrawerPaginationBottom',
    missingTypeAddProjectName: 'caseLibraryMissingTypeAddProjectName',
    missingTypeNameInput: 'caseLibraryMissingTypeNameInput',
    missingTypeAddConfirmBtn: 'caseLibraryMissingTypeAddConfirmBtn',
    missingTypeAddStatus: 'caseLibraryMissingTypeAddStatus',
    missingTypeManageBody: 'caseLibraryMissingTypeManageBody',
    missingTypeManageStatus: 'caseLibraryMissingTypeManageStatus',
    missingAddProjectName: 'caseLibraryMissingAddProjectName',
    missingAddModuleNameInput: 'caseLibraryMissingModuleNameInput',
    missingAddConfirmBtn: 'caseLibraryMissingAddConfirmBtn',
    missingAddStatus: 'caseLibraryMissingAddStatus',
    missingEditProjectName: 'caseLibraryMissingEditProjectName',
    missingEditModuleNameInput: 'caseLibraryMissingEditModuleNameInput',
    missingEditConfirmBtn: 'caseLibraryMissingEditConfirmBtn',
    missingEditStatus: 'caseLibraryMissingEditStatus',
    shareDrawerCaseName: 'caseLibraryShareCaseName',
    shareDrawerSourceProject: 'caseLibraryShareSourceProject',
    shareDrawerSourceVersion: 'caseLibraryShareSourceVersion',
    shareDrawerProjectSelect: 'caseLibraryShareProjectSelect',
    shareDrawerVersionSelect: 'caseLibraryShareVersionSelect',
    shareDrawerConfirmBtn: 'caseLibraryShareConfirmBtn',
    shareDrawerStatus: 'caseLibraryShareStatus',
    selectProjectSelect: 'caseLibrarySelectProjectSelect',
    selectOpenButton: 'openCaseLibrarySelectExecDrawerBtn',
    selectVersionSelect: 'caseLibrarySelectVersionSelect',
    selectSearchInput: 'caseLibrarySelectSearchInput',
    selectConfirmBtn: 'caseLibrarySelectConfirmBtn',
    selectSelectAll: 'caseLibrarySelectSelectAll',
    selectBatchExecBtn: 'caseLibrarySelectBatchExecBtn',
    selectStatus: 'caseLibrarySelectDrawerStatus',
    selectTableHost: 'caseLibrarySelectExecTableHost',
    selectPaginationTop: 'caseLibrarySelectDrawerPaginationTop',
    selectPaginationBottom: 'caseLibrarySelectDrawerPaginationBottom',
    associationCaseName: 'caseLibraryAssociationCaseName',
    associationStatus: 'caseLibraryAssociationStatus',
    associationAddBtn: 'caseLibraryAssociationAddBtn',
    associationListTableHost: 'caseLibraryAssociationListTableHost',
    associationPickStatus: 'caseLibraryAssociationPickStatus',
    associationPickVersionSelect: 'caseLibraryAssociationPickVersionSelect',
    associationPickSearchInput: 'caseLibraryAssociationPickSearchInput',
    associationPickRefreshBtn: 'caseLibraryAssociationPickRefreshBtn',
    associationPickQueryBtn: 'caseLibraryAssociationPickQueryBtn',
    associationPickNextBtn: 'caseLibraryAssociationPickNextBtn',
    associationCandidateTableHost: 'caseLibraryAssociationCandidateTableHost',
    associationPickSubCaseName: 'caseLibraryAssociationPickSubCaseName',
    associationPickSelectAll: 'caseLibraryAssociationPickSelectAll',
    associationItemTableHost: 'caseLibraryAssociationItemTableHost',
    associationPickPaginationTop: 'caseLibraryAssociationPickPaginationTop',
    associationPickPaginationBottom: 'caseLibraryAssociationPickPaginationBottom',
    associationPickConfirmBtn: 'caseLibraryAssociationPickConfirmBtn',
    associationDeleteConfirmBtn: 'caseLibraryAssociationDeleteConfirmBtn',
    importSelectProjectSelect: 'caseLibraryImportSelectProjectSelect',
    importSelectVersionSelect: 'caseLibraryImportSelectVersionSelect',
    importSelectSearchInput: 'caseLibraryImportSelectSearchInput',
    importSelectQueryBtn: 'caseLibraryImportSelectQueryBtn',
    importSelectBatchBtn: 'caseLibraryImportSelectBatchBtn',
    importSelectSelectAll: 'caseLibraryImportSelectSelectAll',
    importSelectStatus: 'caseLibraryImportSelectStatus',
    importSelectListBody: 'caseLibraryImportSelectListBody',
    importSelectPaginationTop: 'caseLibraryImportSelectPaginationTop',
    importSelectPaginationBottom: 'caseLibraryImportSelectPaginationBottom',
    historyDrawerProjectSelect: 'caseLibraryHistoryProjectSelect',
    historyDrawerVersionSelect: 'caseLibraryHistoryVersionSelect',
    historyDrawerSearchInput: 'caseLibraryHistorySearchInput',
    historyDrawerQueryBtn: 'caseLibraryHistoryQueryBtn',
    historyDrawerClearBtn: 'caseLibraryHistoryClearBtn',
    historyDrawerStatus: 'caseLibraryHistoryDrawerStatus',
    historyDrawerTableHost: 'caseLibraryHistoryDrawerTableHost',
    historyDrawerPaginationTop: 'caseLibraryHistoryDrawerPaginationTop',
    historyDrawerPaginationBottom: 'caseLibraryHistoryDrawerPaginationBottom',
    historyDetailCard: 'caseLibraryHistoryDetailCard',
    historyStatus: 'caseLibraryHistoryStatus',
    historyCaseName: 'caseLibraryHistoryCaseName',
    historyRefreshBtn: 'caseLibraryHistoryRefreshBtn',
    historyHideBtn: 'caseLibraryHistoryHideBtn',
    historyAppendPill: 'caseLibraryHistoryAppendPill',
    historyAddedPill: 'caseLibraryHistoryAddedPill',
    historyUpdatedPill: 'caseLibraryHistoryUpdatedPill',
    historyDeletedPill: 'caseLibraryHistoryDeletedPill',
    historyImportPill: 'caseLibraryHistoryImportPill',
    historyReimportPill: 'caseLibraryHistoryReimportPill',
    historyFileDeletedPill: 'caseLibraryHistoryFileDeletedPill',
    historyPaginationTop: 'caseLibraryHistoryPaginationTop',
    historyPaginationBottom: 'caseLibraryHistoryPaginationBottom',
    historyTableHost: 'caseLibraryHistoryTableHost',
  };

  function collectDom(documentRef) {
    var target = {};
    Object.keys(DOM_IDS).forEach(function(key) {
      target[key] = documentRef && typeof documentRef.getElementById === 'function'
        ? documentRef.getElementById(DOM_IDS[key])
        : null;
    });
    return target;
  }

  function createState() {
    return {
      projects: [],
      projectNameById: {},
      versionsByProject: {},
      versionNameByProject: {},
      importDrawer: {
        files: [], projectId: null, versionId: null, loading: false,
      },
      writer: {
        loading: false,
        projectId: null,
        versionId: null,
        draftItems: [],
        draftFileName: '',
        fileNameInput: '',
        fileNameClean: '',
        fileNameDuplicate: false,
        fileNameChecking: false,
        duplicateCaseFileId: null,
        summary: null,
        publishing: false,
        lastImportedCaseFileId: null,
      },
      importDiff: {
        mode: 'import',
        caseFileId: null,
        fileName: '',
        cleanName: '',
        importedCleanName: '',
        source: '',
        projectId: null,
        importVersionId: null,
        dbVersionId: null,
        importItems: [],
        dbItems: [],
        loading: false,
        confirming: false,
      },
      importInvalid: {
        file: null,
        fileName: '',
        cleanName: '',
        source: '',
        projectId: null,
        versionId: null,
        structuralErrors: [],
        items: [],
        invalid: [],
        loading: false,
        locateIndex: -1,
      },
      editDrawer: {
        projectId: null,
        versionId: null,
        ownerFilter: 'all',
        ownerFilterTouched: false,
        changeVersionId: null,
        fileSearchText: '',
        files: [],
        execByFileId: {},
        loading: false,
        selection: new Set(),
        pageIndex: 0,
        restoring: false,
      },
      shareDrawer: {
        caseFile: null,
        caseFiles: [],
        projectId: null,
        versionId: null,
        loading: false,
        versionLoadFailed: false,
        projects: [],
        projectNameById: {},
        versionsByProject: {},
        versionNameByProject: {},
        previousDrawer: null,
        reopenPrevious: false,
      },
      associationDrawer: {
        caseFile: null, processing: false, previousDrawer: null, pendingAction: '', pendingAssociationId: null,
      },
      associationPickDrawer: {
        mode: 'create',
        mainCaseFile: null,
        associationId: null,
        subCaseFile: null,
        originalSubCaseFileId: null,
        originalSelectedCaseItemIds: [],
        versionId: null,
        processing: false,
        previousDrawer: null,
      },
      importSelectDrawer: {
        projectId: null,
        versionId: null,
        searchText: '',
        files: [],
        loading: false,
        processing: false,
        selection: new Set(),
        skipCloseImport: false,
        pageIndex: 0,
        loadSeq: 0,
      },
      historyQueryDrawer: { projectId: null, versionId: null },
      historyDetail: {
        projectId: null, fileNameClean: '', isDeleted: false, versionId: null, restoring: false,
      },
      editor: {
        caseFile: null,
        items: [],
        searchText: '',
        pageIndex: 0,
        batchAddCount: 5,
        selection: new Set(),
        remarkOpen: new Set(),
        pendingOp: null,
        pendingTimer: null,
        pendingInterval: null,
        pendingToast: null,
        pendingRemaining: 0,
        restoring: false,
      },
      aiGen: {
        caseFileId: null,
        requirementText: '',
        requirementFileName: '',
        loading: false,
        generated: false,
        error: '',
        modules: [],
        selection: new Set(),
        taskSignature: '',
        taskId: '',
      },
      missingReminder: {
        projectId: null,
        signature: '',
        items: [],
        matchedModules: [],
        matchedTypes: [],
        loading: false,
        loaded: false,
        seq: 0,
        refreshTimer: null,
      },
      missingDrawer: {
        projectId: null,
        moduleId: null,
        modules: [],
        loading: false,
        processing: false,
        selection: new Set(),
        pageIndex: 0,
        moduleCompletion: {},
        moduleCompletionLoading: {},
        moduleCompletionSeq: 0,
      },
      missingType: { projectId: null, types: [], loading: false, selection: new Set() },
      missingTypeAdd: { projectId: null, loading: false, source: '' },
      missingTypeManage: { loading: false },
      missingAdd: { projectId: null, loading: false },
      missingEdit: { moduleId: null, projectId: null, name: '', loading: false },
      missingView: {
        projectId: null,
        modules: [],
        moduleIds: [],
        items: [],
        selection: new Set(),
        pageIndex: 0,
        restoring: false,
        pendingOp: null,
        pendingTimer: null,
        pendingInterval: null,
        pendingToast: null,
        pendingRemaining: 0,
        autoSaveTimers: {},
        autoSaveInFlight: {},
        typeFilters: new Set(),
      },
      missingImport: {
        projectId: null,
        files: [],
        items: [],
        structuralErrors: [],
        loading: false,
        pending: false,
        invalid: [],
      },
      missingImportDiff: {
        projectId: null,
        rows: [],
        newItems: [],
        duplicateCount: 0,
        pendingItemsByModule: [],
        structuralErrors: [],
      },
    };
  }

  function create(options) {
    var opts = options && typeof options === 'object' ? options : {};
    return {
      dom: collectDom(opts.document || null),
      state: createState(),
    };
  }

  return {
    create: create,
    collectDom: collectDom,
    createState: createState,
  };
});
