(function() {
  window.app = window.app || {};
  window.app.domConfig = {
    ids: [
      'fileInput', 'dropZone', 'fileName', 'rawText', 'parseStatus', 'reviewStatus', 'clarifyStatus', 'reviewViewContainer', 'splitViewContainer',
      'cleanViewContainer', 'cleanHighlightAllBtn', 'toggleCleanViewBtn', 'cleanRawView', 'toggleCleanRawViewBtn', 'cleanRawLocateBtn',
      'caseStatus', 'caseViewBtn', 'caseViewContainer', 'caseViewHint', 'autoRawDropZone', 'autoCaseDropZone', 'tempExecDropZone',
      'tempExecInput', 'tempExecStatus', 'tempExecNav', 'tempFocusBlock', 'tempVersionGrid', 'createTempVersionBtn', 'tempExecView',
      'tempExecMindContainer', 'exportTempExecBtn', 'exportTempExecConfigBtn', 'importTempExecBtn', 'exportTempExecXmindBtn', 'exportTempExecCasesXmindBtn', 'tempExecXmindViewBtn',
      'importTempExecConfigBtn', 'tempExecMindBtn', 'tempExecOverview', 'tempExecBackBtn', 'importTempExecFile',
      'importTempExecConfigFile', 'autoClarifyContainer', 'autoClarifyStatus', 'autoClarifyToggleBtn', 'goUsecaseGenBtn',
      'toggleTempVersion',
      'tempExecToolbarCard', 'tempExecToolbar',
      'openTempExecDrawerBtn', 'closeTempExecDrawerBtn', 'tempExecDrawer',
      'casesGoUsecaseGenBtn', 'casesGenerationContainer', 'caseGenProgressPanel', 'caseGenProgressList', 'caseGenProgressToggle',
      'sidebarTabs', 'sidebarTabBar', 'sidebarTabPanels', 'sidebarTabCasegen', 'sidebarTabMemo', 'caseGenProgressTabDot',
      'memoPadPanel', 'memoPadToggle', 'memoTabLayer', 'memoTabList', 'memoTabAddBtn', 'memoPadBody', 'memoTabProgress',
      'cleanStatus', 'compareStatus', 'compareCaseAssistantStatus',
      'splitStatus', 'casesCoverageStatus', 'caseGenStatus', 'autoWorkflowStatus', 'casesModuleProgress', 'exportCaseGen', 'exportCaseGenXmind',
      'toSplitFromCaseGen', 'appendToExistingCases', 'appendTargetSelect', 'transferSelectedToExec', 'saveRawDebugBtn', 'importRawDebugBtn', 'saveCleanDebugBtn', 'importCleanDebugBtn', 'saveSplitDebugBtn',
      'importSplitDebugBtn', 'saveCaseDebugBtn', 'importCaseDebugBtn', 'scrollTopBtn', 'scrollBottomBtn', 'currentPath', 'currentPathText', 'xmindStructureToggle',
      'xmindStructureCard', 'caseFileInput', 'caseDropZone', 'caseStatus', 'caseViewBtn', 'caseViewContainer', 'caseViewHint',
      'caseGenViewDrawer', 'caseGenViewDrawerBody', 'caseGenViewDrawerTitle', 'caseGenAllSelectBtn', 'closeCaseGenViewDrawerBtn',
      'reviewViewDrawer', 'reviewViewDrawerBody', 'reviewViewDrawerTitle', 'closeReviewViewDrawerBtn',
      'cleanViewDrawer', 'cleanViewDrawerBody', 'cleanViewDrawerTitle', 'closeCleanViewDrawerBtn',
      'splitViewDrawer', 'splitViewDrawerBody', 'splitViewDrawerTitle', 'closeSplitViewDrawerBtn',
      'caseViewDrawer', 'caseViewDrawerBody', 'caseViewDrawerTitle', 'closeCaseViewDrawerBtn',
      'missingViewDrawer', 'missingViewDrawerBody', 'missingViewDrawerTitle', 'closeMissingViewDrawerBtn',
      'autoClarifyDrawer', 'autoClarifyDrawerBody', 'autoClarifyDrawerTitle', 'closeAutoClarifyDrawerBtn',
      'autoCompareDrawer', 'autoCompareDrawerBody', 'autoCompareDrawerTitle', 'closeAutoCompareDrawerBtn', 'autoCompareToggleBtn', 'autoCompareStatusSummary',
      'autoMissingDrawer', 'autoMissingDrawerBody', 'autoMissingDrawerTitle', 'closeAutoMissingDrawerBtn',
    ],
    alias: [
      { name: 'toSplitFromCaseGenBtn', id: 'toSplitFromCaseGen' },
      { name: 'appendTargetSelect', id: 'appendTargetSelect' },
      { name: 'appendToExistingCasesBtn', id: 'appendToExistingCases' },
      { name: 'transferSelectedToExecBtn', id: 'transferSelectedToExec' },
      { name: 'exportCaseGenBtn', id: 'exportCaseGen' },
      { name: 'exportCaseGenXmindBtn', id: 'exportCaseGenXmind' },
      { name: 'runReviewBtn', id: 'runReview' },
      { name: 'reviewResultEl', id: 'reviewResult' },
      { name: 'copyReviewResultBtn', id: 'copyReviewResult' },
      { name: 'exportReviewResultBtn', id: 'exportReviewResult' },
      { name: 'importReviewResultBtn', id: 'importReviewResult' },
      { name: 'reviewImportFileInput', id: 'reviewImportFile' },
      { name: 'toggleReviewViewBtn', id: 'toggleReviewView' },
      { name: 'confirmClarificationsBtn', id: 'confirmClarifications' },
      { name: 'toggleSplitViewBtn', id: 'toggleSplitView' },
      { name: 'runCleanBtn', id: 'runClean' },
      { name: 'copyBtn', id: 'copyCleaned' },
      { name: 'cleanedTextEl', id: 'cleanedText' },
      { name: 'compareResultEl', id: 'compareResult' },
      { name: 'casesCompareResultEl', id: 'casesCompareResult' },
      { name: 'splitResultEl', id: 'splitResult' },
      { name: 'caseFileListEl', id: 'caseFileList' },
      { name: 'caseTextEl', id: 'caseText' },
      { name: 'autoRawInput', id: 'autoRawFile' },
      { name: 'autoRawListEl', id: 'autoRawFileList' },
      { name: 'autoRawClearBtn', id: 'autoRawClear' },
      { name: 'autoCaseInput', id: 'autoCaseFile' },
      { name: 'autoCaseFileListEl', id: 'autoCaseFileList' },
      { name: 'autoWorkflowBtn', id: 'runAutoWorkflow' },
      { name: 'autoClarifyToggle', id: 'autoNeedClarify' },
      { name: 'autoClarifyConfirmBtn', id: 'autoClarifyConfirm' },
      { name: 'autoMissingGoUsecaseBtn', id: 'autoMissingGoUsecase' },
      { name: 'cleanTimingEl', id: 'cleanTiming' },
      { name: 'reviewTimingEl', id: 'reviewTiming' },
      { name: 'compareTimingEl', id: 'compareTiming' },
      { name: 'splitBtnEl', id: 'splitBtn' },
      { name: 'splitTimingEl', id: 'splitTiming' },
      { name: 'casesTimingEl', id: 'casesTiming' },
      { name: 'caseGenTimingEl', id: 'caseGenTiming' },
      { name: 'rawDebugFileInput', id: 'rawDebugFile' },
      { name: 'cleanDebugFileInput', id: 'cleanDebugFile' },
      { name: 'splitDebugFileInput', id: 'splitDebugFile' },
      { name: 'caseDebugFileInput', id: 'caseDebugFile' },
      { name: 'saveRawDebugBtn', id: 'saveRawDebug' },
      { name: 'importRawDebugBtn', id: 'importRawDebug' },
      { name: 'saveCleanDebugBtn', id: 'saveCleanDebug' },
      { name: 'importCleanDebugBtn', id: 'importCleanDebug' },
      { name: 'saveSplitDebugBtn', id: 'saveSplitDebug' },
      { name: 'importSplitDebugBtn', id: 'importSplitDebug' },
      { name: 'saveCaseDebugBtn', id: 'saveCaseDebug' },
      { name: 'importCaseDebugBtn', id: 'importCaseDebug' },
    ],
  };
})();
