(function() {
  window.app = window.app || {};
  window.app.domConfig = {
    ids: [
      'fileInput', 'fileName', 'rawText',
      'caseStatus', 'caseViewBtn', 'caseViewContainer', 'caseViewHint', 'tempExecDropZone',
      'tempExecInput', 'tempExecStatus', 'tempExecNav', 'tempFocusBlock', 'tempVersionGrid', 'createTempVersionBtn', 'tempExecView',
      'tempExecMindContainer', 'exportTempExecBtn', 'exportTempExecConfigBtn', 'importTempExecBtn', 'exportTempExecXmindBtn', 'exportTempExecCasesXmindBtn', 'tempExecXmindViewBtn',
      'importTempExecConfigBtn', 'tempExecMindBtn', 'tempExecOverview', 'tempExecBackBtn', 'importTempExecFile',
      'importTempExecConfigFile',
      'toggleTempVersion',
      'tempExecContextTitle', 'tempExecToolbarCard', 'tempExecToolbar',
      'openTempExecDrawerBtn', 'closeTempExecDrawerBtn', 'tempExecDrawer',
      'casesGenerationContainer', 'caseGenProgressPanel', 'caseGenProgressList', 'caseGenProgressToggle',
      'sidebarTabs', 'sidebarTabBar', 'sidebarTabPanels', 'sidebarTabCasegen', 'sidebarTabMemo', 'caseGenProgressTabDot',
      'memoPadPanel', 'memoPadToggle', 'memoTabLayer', 'memoTabList', 'memoTabAddBtn', 'memoPadBody', 'memoTabProgress',
      'casesCoverageStatus', 'caseGenStatus', 'casesModuleProgress',
      'xmindCaseGenModelSelect', 'xmindCaseGenPrompt', 'xmindCaseGenTemperature', 'xmindCaseGenReasoning', 'testXmindCaseGenModel', 'xmindCaseGenAssignStatus',
      'xmindStructureToggle',
      'xmindStructureCard', 'caseFileInput', 'caseDropZone', 'caseStatus', 'caseViewBtn', 'caseViewContainer', 'caseViewHint',
      'xmindCaseGenOpenBtn', 'xmindCaseGenDrawer', 'xmindCaseGenDrawerTitle', 'xmindCaseGenDrawerBody', 'closeXmindCaseGenDrawerBtn',
      'xmindCaseGenHomeProgress', 'xmindCaseGenHomeProgressPercent', 'xmindCaseGenHomeProgressTrack', 'xmindCaseGenHomeProgressFill', 'xmindCaseGenHomeProgressMeta', 'xmindCaseGenHomeProgressList',
      'xmindCaseGenWorkspaceLayer', 'xmindCaseGenWorkspaceList', 'xmindCaseGenWorkspaceAddBtn',
      'xmindCaseGenToolbar', 'xmindCaseGenSummaryBtn', 'xmindCaseGenKnowledgeRuleBtn', 'xmindCaseGenKnowledgeAiBtn', 'xmindCaseGenDedupeBtn', 'xmindCaseGenCoverageBtn', 'xmindCaseGenSummaryOverlay', 'xmindCaseGenSummaryDialog', 'xmindCaseGenSummaryDialogBody', 'xmindCaseGenSummaryCloseBtn',
      'xmindCaseGenRequirementBadge', 'xmindCaseGenRequirementSummary', 'xmindCaseGenRequirementMeta',
      'xmindCaseGenCasesBadge', 'xmindCaseGenCasesSummary', 'xmindCaseGenCasesMeta',
      'xmindCaseGenImportRequirementBtn', 'xmindCaseGenImportCasesBtn', 'xmindCaseGenSelectCasesBtn',
      'xmindCaseGenGenerateModulesBtn', 'xmindCaseGenGenerateFullBtn', 'xmindCaseGenExportBtn', 'xmindCaseGenExportMarkdownBtn', 'xmindCaseGenPromptBtn',
      'xmindCaseGenStatus', 'xmindCaseGenMindContainer',
      'knowledgeBaseBaseUrlInput', 'saveKnowledgeBaseBaseUrl', 'validateKnowledgeBaseBaseUrl', 'knowledgeBaseBaseUrlStatus',
      'caseViewDrawer', 'caseViewDrawerBody', 'caseViewDrawerTitle', 'closeCaseViewDrawerBtn',
      'missingViewDrawer', 'missingViewDrawerBody', 'missingViewDrawerTitle', 'closeMissingViewDrawerBtn',
    ],
    alias: [
      { name: 'caseFileListEl', id: 'caseFileList' },
      { name: 'caseTextEl', id: 'caseText' },
      { name: 'autoCaseFileListEl', id: 'autoCaseFileList' },
    ],
  };
})();
